/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuildingResponseBuildingDetails } from './buildingResponseBuildingDetails';


export interface BuildingResponse { 
    data_rows: Array<BuildingResponseBuildingDetails>;
}

