/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterMessageResponseFilterData } from './filterMessageResponseFilterData';


export interface FilterMessageResponse { 
    data_rows: Array<FilterMessageResponseFilterData>;
}

