/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginResponse { 
    authenticated: boolean;
    is_2fa_verified: boolean;
    management_privilege: boolean;
    status: boolean;
}

