/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MainPagedHandoverMessageResponseMainHandoverMessageRow } from './mainPagedHandoverMessageResponseMainHandoverMessageRow';


export interface MainPagedHandoverMessageResponse { 
    data_count: number;
    data_rows: Array<MainPagedHandoverMessageResponseMainHandoverMessageRow>;
}

