/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditRequestLivingSpaceData } from './managementServiceUserEditRequestLivingSpaceData';
import { ManagementServiceUserEditRequestServiceUserNickName } from './managementServiceUserEditRequestServiceUserNickName';


export interface ManagementServiceUserEditRequestServiceUserData { 
    ID: number;
    active: boolean;
    deleted: boolean;
    living_space: ManagementServiceUserEditRequestLivingSpaceData | null;
    name: string;
    service_user_nicknames: Array<ManagementServiceUserEditRequestServiceUserNickName>;
    start_date: string;
}

