/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementLivingSpaceResponseBuildingData } from './managementLivingSpaceResponseBuildingData';


export interface ManagementLivingSpaceResponseFloorData { 
    ID: number;
    building: ManagementLivingSpaceResponseBuildingData;
    floor_name: string;
}

