/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementEmployeeResponseEmployeeDetails } from './managementEmployeeResponseEmployeeDetails';


export interface ManagementEmployeeResponse { 
    data_rows: Array<ManagementEmployeeResponseEmployeeDetails>;
}

