/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementEmployeeEditRequestEmployeeDetails } from './managementEmployeeEditRequestEmployeeDetails';


export interface ManagementEmployeeEditRequest { 
    after: ManagementEmployeeEditRequestEmployeeDetails;
    before: ManagementEmployeeEditRequestEmployeeDetails;
}

