/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditRequestBuildingData } from './managementServiceUserEditRequestBuildingData';


export interface ManagementServiceUserEditRequestFloorData { 
    ID: number;
    building: ManagementServiceUserEditRequestBuildingData;
    floor_name: string;
}

