/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserResponseBuildingData } from './managementServiceUserResponseBuildingData';


export interface ManagementServiceUserResponseFloorData { 
    ID: number;
    building: ManagementServiceUserResponseBuildingData;
    floor_name: string;
}

