/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditRequestServiceUserData } from './managementServiceUserEditRequestServiceUserData';


export interface ManagementServiceUserEditRequest { 
    after: ManagementServiceUserEditRequestServiceUserData;
    before: ManagementServiceUserEditRequestServiceUserData;
}

