/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManagementEmployeeEditResponseAuth { 
    ID: number;
    account: string;
    password: string;
    totp_secret?: string | null;
}

