/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementLivingSpaceResponseFloorData } from './managementLivingSpaceResponseFloorData';


export interface ManagementLivingSpaceResponseLivingSpaceData { 
    ID: number;
    floor: ManagementLivingSpaceResponseFloorData;
    name: string;
}

