/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserResponseServiceUserData } from './managementServiceUserResponseServiceUserData';


export interface ManagementServiceUserResponse { 
    data_rows: Array<ManagementServiceUserResponseServiceUserData>;
}

