/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserResponseFloorData } from './managementServiceUserResponseFloorData';


export interface ManagementServiceUserResponseLivingSpaceData { 
    ID: number;
    floor: ManagementServiceUserResponseFloorData;
    name: string;
}

