/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementLivingSpaceResponseLivingSpaceData } from './managementLivingSpaceResponseLivingSpaceData';


export interface ManagementLivingSpaceResponse { 
    data_rows: Array<ManagementLivingSpaceResponseLivingSpaceData>;
}

