/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditResponseServiceUserNickName } from './managementServiceUserEditResponseServiceUserNickName';
import { ManagementServiceUserEditResponseLivingSpaceData } from './managementServiceUserEditResponseLivingSpaceData';


export interface ManagementServiceUserEditResponseServiceUserData { 
    ID: number;
    active: boolean;
    deleted: boolean;
    living_space: ManagementServiceUserEditResponseLivingSpaceData | null;
    name: string;
    service_user_nicknames: Array<ManagementServiceUserEditResponseServiceUserNickName>;
    start_date: string;
}

