/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditResponseBuildingData } from './managementServiceUserEditResponseBuildingData';


export interface ManagementServiceUserEditResponseFloorData { 
    ID: number;
    building: ManagementServiceUserEditResponseBuildingData;
    floor_name: string;
}

