/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManagementServiceUserEditResponseFloorData } from './managementServiceUserEditResponseFloorData';


export interface ManagementServiceUserEditResponseLivingSpaceData { 
    ID: number;
    floor: ManagementServiceUserEditResponseFloorData;
    name: string;
}

