/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NewEmployeeRequest { 
    account: string;
    email: string;
    name: string;
    password: string;
    use_two_factor: boolean;
}

