/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewMessageInputGenericSelectObject } from './newMessageInputGenericSelectObject';


export interface NewMessageInputSecondaryInput { 
    message_body: string;
    message_type: NewMessageInputGenericSelectObject;
}

