/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NewMessageInputGenericSelectObject } from './newMessageInputGenericSelectObject';
import { NewMessageInputSecondaryInput } from './newMessageInputSecondaryInput';


export interface NewMessageInput { 
    creator: NewMessageInputGenericSelectObject;
    datetime: string;
    locations: Array<NewMessageInputGenericSelectObject>;
    secondary_data: Array<NewMessageInputSecondaryInput>;
    shift: NewMessageInputGenericSelectObject;
}

