/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SecondaryEditRequestSecondaryMessageDetail { 
    ID: number;
    'delete': boolean;
    message_body: string;
}

