/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecondaryEditRequestSecondaryMessageDetail } from './secondaryEditRequestSecondaryMessageDetail';


export interface SecondaryEditRequest { 
    after: SecondaryEditRequestSecondaryMessageDetail;
    before: SecondaryEditRequestSecondaryMessageDetail;
}

