/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecondaryHandoverMessageResponseSecondaryHandoverMessageRow } from './secondaryHandoverMessageResponseSecondaryHandoverMessageRow';


export interface SecondaryHandoverMessageResponse { 
    data_count: number;
    data_rows: Array<SecondaryHandoverMessageResponseSecondaryHandoverMessageRow>;
}

