/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SecondaryEditResponseSecondaryMessageDetail { 
    ID: number;
    is_deleted: boolean;
    message_body: string;
    message_type_id: number;
}

