/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecondaryEditResponseSecondaryMessageDetail } from './secondaryEditResponseSecondaryMessageDetail';


export interface SecondaryEditResponse { 
    msg: SecondaryEditResponseSecondaryMessageDetail;
    status: string;
}

