/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceUserInputServiceUserInputData } from './serviceUserInputServiceUserInputData';


export interface ServiceUserInput { 
    data_rows: Array<ServiceUserInputServiceUserInputData>;
}

