/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SingleHandoverMessageSecondaryHandoverMessageRow } from './singleHandoverMessageSecondaryHandoverMessageRow';


export interface SingleHandoverMessage { 
    secondary_messages: Array<SingleHandoverMessageSecondaryHandoverMessageRow>;
}

