/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SingleHandoverMessageSecondaryHandoverMessageRow { 
    ID: number;
    creator_id: number;
    creator_name: string;
    location_ids: Array<number>;
    location_names: Array<string>;
    message_body: string;
    message_type_id: number;
    message_type_name: string;
    shift_id: number;
    shift_name: string;
    timestamp: string;
}

