/**
 * APIFlask
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationErrorDetail } from './validationErrorDetail';


export interface ValidationError { 
    detail?: ValidationErrorDetail;
    message?: string;
}

